# Generated by Django 5.1.1 on 2024-10-26 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_shippingaddress_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
