# Generated by Django 5.1.1 on 2024-10-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address1",
            new_name="shipping_address",
        ),
    ]
