# Generated by Django 5.1.1 on 2024-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_rename_shipping_address1_order_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
