# Generated by Django 5.1.1 on 2024-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
