# Generated by Django 5.1.4 on 2025-01-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_order_is_via_esewa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_via_esewa",
        ),
    ]
