# Generated by Django 5.1.4 on 2025-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_remove_order_is_via_esewa"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="epay",
            field=models.BooleanField(default=False),
        ),
    ]
