# Generated by Django 5.1.2 on 2024-10-20 15:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_first_name", models.CharField(max_length=50)),
                ("customer_last_name", models.CharField(max_length=50)),
                (
                    "customer_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("customer_email", models.EmailField(max_length=10)),
                ("customer_password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.CharField(max_length=50)),
                (
                    "product_description",
                    models.CharField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                ("product_image", models.ImageField(upload_to="uploads/product/")),
                (
                    "product_category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_quantity", models.IntegerField(default=1)),
                (
                    "order_address",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "order_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("order_date", models.DateField(default=datetime.date.today)),
                ("order_status", models.BooleanField(default=False)),
                (
                    "order_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.customer"
                    ),
                ),
                (
                    "order_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.product"
                    ),
                ),
            ],
        ),
    ]
