# Generated by Django 5.1.2 on 2024-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
