# Generated by Django 5.1.2 on 2024-10-20 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_categories_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_rating",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_tag",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
