# Generated by Django 5.1.2 on 2024-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_product_product_rating_product_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_discount_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
