# Generated by Django 5.1.2 on 2024-10-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_product_product_discount_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_discount_price",
            new_name="product_marked_price",
        ),
    ]
