# Generated by Django 5.1.2 on 2024-10-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_alter_product_product_marked_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_marked_price",
            new_name="product_sale_price",
        ),
    ]
