# Generated by Django 5.1.2 on 2024-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0007_rename_product_marked_price_product_product_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
