# Generated by Django 5.1.2 on 2024-10-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0010_product_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_slug",
            new_name="slug",
        ),
    ]
