# Generated by Django 5.1.2 on 2024-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0011_rename_product_slug_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_tag",
        ),
        migrations.AddField(
            model_name="product",
            name="product_tag",
            field=models.ManyToManyField(blank=True, to="Home.tag"),
        ),
    ]
