# Generated by Django 5.1.1 on 2024-10-25 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0012_tag_remove_product_product_tag_product_product_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("address1", models.CharField(blank=True, max_length=200)),
                ("address2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("zipcode", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
