# Generated by Django 5.1.1 on 2024-10-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0013_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
