# Generated by Django 5.1.2 on 2024-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0014_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
