# Generated by Django 5.1.2 on 2024-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0015_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(null=True, upload_to="uploads/product/"),
        ),
    ]
