# Generated by Django 5.1.2 on 2024-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0016_alter_product_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
            ],
        ),
    ]
