# Generated by Django 5.1.2 on 2024-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0017_inquiry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={"verbose_name": "User Inquires"},
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
