# Generated by Django 5.1.3 on 2024-11-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0018_alter_inquiry_options_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_long_description",
            field=models.CharField(blank=True, default="", max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
