# Generated by Django 5.1.3 on 2024-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0019_product_product_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_long_description",
            field=models.TextField(blank=True, default="", max_length=1500, null=True),
        ),
    ]
