# Generated by Django 5.1.3 on 2024-11-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0020_alter_product_product_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_additional_information",
            field=models.TextField(blank=True, default="", max_length=500, null=True),
        ),
    ]
