# Generated by Django 5.1.3 on 2024-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0021_product_product_additional_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="category_display_image",
            field=models.ImageField(null=True, upload_to="uploads/product/"),
        ),
    ]
