# Generated by Django 5.1.3 on 2024-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0022_categories_category_display_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
