# Generated by Django 5.1.3 on 2024-11-21 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0023_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_long_description",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True),
        ),
    ]
