# Generated by Django 5.1.3 on 2024-11-21 15:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0024_alter_product_product_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_long_description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
