# Generated by Django 5.1.3 on 2024-11-23 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0026_alter_product_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
