# Generated by Django 5.1.3 on 2024-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0028_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
