# Generated by Django 5.1.3 on 2024-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0029_alter_categories_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50),
        ),
    ]
