# Generated by Django 5.1.3 on 2024-12-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0030_alter_product_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
