# Generated by Django 5.1.3 on 2024-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0032_inquiry_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiry",
            name="created_at",
        ),
        migrations.AddField(
            model_name="inquiry",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
