# Generated by Django 5.1.4 on 2024-12-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0034_alter_product_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
