# Generated by Django 5.1.4 on 2024-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0035_alter_product_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_long_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
