# Generated by Django 5.1.4 on 2024-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0036_alter_product_product_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
