# Generated by Django 5.1.4 on 2024-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0038_inquiry_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="subject",
            field=models.CharField(max_length=20),
        ),
    ]
