# Generated by Django 5.1.4 on 2024-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0039_alter_inquiry_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="subject",
            field=models.CharField(max_length=50),
        ),
    ]
