# Generated by Django 5.1.4 on 2024-12-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0042_userreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="review_for",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home.product",
            ),
        ),
    ]
