# Generated by Django 5.1.4 on 2024-12-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0043_userreview_review_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="review",
            field=models.TextField(max_length=100),
        ),
    ]
