# Generated by Django 5.1.4 on 2025-01-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0046_alter_userreview_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_rating",
        ),
    ]
