# Generated by Django 5.1.4 on 2025-01-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0047_remove_product_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="uploads/lower_hero_section/"
                    ),
                ),
            ],
        ),
    ]
