# Generated by Django 5.1.4 on 2025-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0048_herosectionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
