# Generated by Django 5.1.4 on 2025-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0049_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_additional_information",
            field=models.TextField(blank=True, default="", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
