from django.urls import path
from . import views

urlpatterns = [
    path('admin-dashboard', views.DashboardView, name='admin-dashboard'),
    path('all-products', views.AllProductsView, name='all-products'),
    path('admin-all-blogs', views.AllBlogsView, name='admin-all-blogs'),
    path('all-categories', views.AllCategoriesView, name='all-categories'),
    path('all-tags', views.AllTagsView, name='all-tags'),
    path('add-product', views.AddProductView, name='add-product'),
    path('add-post', views.AddPostView, name='add-post'),
    path('add-tag', views.AddTagView, name='add-tag'),
    path('edit-product/<int:product_id>',
         views.EditProductView, name='edit-product'),
    path('edit-category/<int:category_id>',
         views.EditCategoryView, name='edit-category'),
    path('edit-blog/<int:blog_id>',
         views.EditBlogView, name='edit-blog'),
    path('edit-tag/<int:tag_id>',
         views.EditTagView, name='edit-tag'),
    path('delete-product/<int:product_id>',
         views.DeleteProductsView, name='delete-product'),
    path('delete-category/<int:category_id>',
         views.DeleteCategoryView, name='delete-category'),
    path('delete-post/<int:post_id>',
         views.DeletePostView, name='delete-post'),
    path('delete-tag/<int:tag_id>',
         views.DeleteTagView, name='delete-tag'),
    path('add-category', views.AddCategoryView, name='add-category'),

    path("admin-search/", views.AdminSearchView, name='admin-search'),
    path('all-blog-categories', views.AllBlogCategoryView,
         name='all-blog-categories'),
    path('add-blog-category', views.AddBlogCategoryView, name='add-blog-category'),

    path('edit-blog-category/<int:category_id>',
         views.EditBlogCategoryView, name='edit-blog-category'),
    path('delete-blog-category/<int:category_id>',
         views.DeleteBlogCategoryView, name='delete-blog-category'),

    path('all-blog-tags', views.AllBlogTagView,
         name='all-blog-tags'),
    path('add-blog-tag', views.AddBlogTagView, name='add-blog-tag'),

    path('edit-blog-tag/<int:tag_id>',
         views.EditBlogTagView, name='edit-blog-tag'),
    path('delete-blog-tag/<int:tag_id>',
         views.DeleteBlogTagView, name='delete-blog-tag'),
    path('admin-all-users', views.AllUsersView, name='admin-all-users'),
    path('all-user-inquiries', views.UserInquiriesView, name='all-user-inquiries'),
    path('single-user-inquiry/<int:inquiry_id>',
         views.SingleInquiryView, name='single-user-inquiry'),
    path('website-customization', views.WebsiteCustomizationView,
         name='website-customization'),
    path('add-banner-image', views.AddBannerImageView, name='add-banner-image'),
    path('add-hero-image', views.AddHeroSectionImageView, name='add-hero-image'),
    path('edit-banner-image/<int:banner_id>',
         views.EditBannerImageView, name='edit-banner-image'),
    path('edit-hero-image/<int:hero_section_id>',
         views.EditHeroSectionImageView, name='edit-hero-image'),
    path('delete-banner-image/<int:banner_id>',
         views.DeleteBannerImageView, name='delete-banner-image'),
    path('delete-hero-image/<int:hero_section_id>',
         views.DeleteHeroSectionImageView, name='delete-hero-image')

]
